format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

right_format = """
$status\
$cmd_duration\
$time"""

add_newline = false
continuation_prompt = '[▶▶](dimmed white) '

[username]
show_always = true
style_user = "green"
format = '[\[$user]($style)'

[hostname]
ssh_only = false
style = "green"
format = '[:]($style)[$hostname\]](green) '

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "red"
only_attached = false

[git_status]
format = '([\[$all_status\]]($style))'
style = "red"
disabled = false
conflicted = "=$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
untracked = "?$count"
stashed = "*$count"
modified = "!$count"
staged = "+$count"
renamed = "^$count"
deleted = "-$count"

[character]
success_symbol = "[ ▶](dimmed white)"
error_symbol = "[ ▶](dimmed red)"
vimcmd_symbol = "[ ◀](green)"

[status]
style = "dimmed red"
format = '[\($status\) ]($style)'
disabled = false

[cmd_duration]
style = "dimmed yellow"
format = '[$duration]($style) '

[time]
disabled = false
style = "yellow"
format = '[\[$time\]]($style) '
